

MAX_LENGTH_PROVEEDOR_ID = 255
MAX_LENGTH_RAZON_SOCIAL = 255
MAX_LENGTH_ABREVIATURA = 255

MAX_LENGTH_ORDEN_COMPRA_ID = 255

MAX_LENGTH_PRODUCTO_ID = 255
MAX_LENGTH_PRODUCTO_DESCRIPCION = 255

MAX_LENGTH_MOVIMIENTO_ID = 255
MAX_LENGTH_MOVIMIENTO_DESCRIPCION_ID = 255
MAX_LENGTH_MOVIMIENTO_DESCRIPCION = 255

MAX_LENGTH_ALMACEN_ID = 255
MAX_LENGTH_ALMACEN_NOMBRE = 255

MAX_LENGTH_GUIA_PROVEEDOR_NRO_SERIE = 255
MAX_LENGTH_GUIA_PROVEEDOR_NRO_CORRELATIVO = 255

MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_ID = 255

MAX_LENGTH_HILADO_ID = 255
MAX_LENGTH_HILADO_TITULO = 255
MAX_LENGTH_HILADO_FIBRA = 255
MAX_LENGTH_HILADO_PROCEDENCIA = 255
MAX_LENGTH_HILADO_ACABADO = 255

MAX_LENGTH_TEJIDO_ID = 255
MAX_LENGTH_TEJIDO_NOMBRE = 255

MAX_LENGTH_CRUDO_ID = 255

MAX_LENGTH_CODIGO_LOTE = 255

MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_ESTADO = 255
MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_ESTADO_DETALLE = 255