MAX_LENGTH_PROVEEDOR_ID = 255
MAX_LENGTH_PROVEEDOR_RAZON_SOCIAL = 255
MAX_LENGTH_PROVEEDOR_ALIAS = 255

MAX_LENGTH_SERVICIO_NOMBRE = 255

MAX_LENGTH_ORDEN_COMPRA_ID = 255

MAX_LENGTH_PRODUCTO_ID = 255
MAX_LENGTH_PRODUCTO_DESCRIPCION = 255

MAX_LENGTH_MOVIMIENTO_ID = 255
MAX_LENGTH_MOVIMIENTO_DESCRIPCION_ID = 255
MAX_LENGTH_MOVIMIENTO_DESCRIPCION = 255

MAX_LENGTH_ALMACEN_ID = 255
MAX_LENGTH_ALMACEN_NOMBRE = 255

MAX_LENGTH_GUIA_PROVEEDOR_NRO_SERIE = 255
MAX_LENGTH_GUIA_PROVEEDOR_NRO_CORRELATIVO = 255

MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_ID = 255

MAX_LENGTH_HILADO_ID = 255
MAX_LENGTH_HILADO_TITULO = 255
MAX_LENGTH_HILADO_FIBRA = 255
MAX_LENGTH_HILADO_PROCEDENCIA = 255
MAX_LENGTH_HILADO_ACABADO = 255

MAX_LENGTH_TEJIDO_ID = 255
MAX_LENGTH_TEJIDO_NOMBRE = 255

MAX_LENGTH_CRUDO_ID = 255

MAX_LENGTH_CODIGO_LOTE = 255

MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_ESTADO = 255
MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_DETALLE_ESTADO = 255

MAX_LENGTH_COLOR_NOMBRE = 255
MAX_LENGTH_COLOR_DESCRIPCION = 255

MAX_LENGTH_ORDEN_SERVICIO_TINTORERIA_ESTADO = 255
MAX_LENGTH_ORDEN_SERVICIO_TINTORERIA_CODIGO_MECSA = 255

MAX_LENGTH_ADMDTABLA_TABLA = 8
MAX_LENGTH_ADMDTABLA_NOMBRE = 80
MAX_LENGTH_ADMDTABLA_VARCHAR1 = 16
MAX_LENGTH_ADMDTABLA_VARCHAR3 = 16

MAX_LENGTH_MECSA_COLOR_ID = 8
MAX_LENGTH_MECSA_COLOR_NAME = MAX_LENGTH_ADMDTABLA_NOMBRE
MAX_LENGTH_MECSA_COLOR_SKU = MAX_LENGTH_ADMDTABLA_VARCHAR1
MAX_LENGTH_MECSA_COLOR_HEXADECIMAL = 9

CODCIA_MAX_LENGTH = 6
PURCHASE_ORDER_TYPE_MAX_LENGTH = 2
PURCHASE_ORDER_NUMBER_MAX_LENGTH = 20
SUPPLIER_CODE_MAX_LENGTH = 22
PAYMENT_METHOD_MAX_LENGTH = 120
STATUS_FLAG_MAX_LENGTH = 2

PRODUCT_CODE_MAX_LENGTH = 22
SUPPLIER_CODE_MAX_LENGTH = 30
UNIT_CODE_MAX_LENGTH = 6

MECSA_COLOR_ID_MAX_LENGTH = 8

PRODUCT_ID_MAX_LENGTH = 12

FIBER_ID_MAX_LENGTH = PRODUCT_ID_MAX_LENGTH
FIBER_DENOMINATION_MAX_LENGTH = 100
FIBER_ORIGIN_MAX_LENGTH = 5

STORAGE_CODE_MAX_LENGTH = 6

