MAX_LENGTH_PROVEEDOR_ID = 255
MAX_LENGTH_PROVEEDOR_RAZON_SOCIAL = 255
MAX_LENGTH_PROVEEDOR_ALIAS = 255

MAX_LENGTH_SERVICIO_NOMBRE = 255

MAX_LENGTH_ORDEN_COMPRA_ID = 255

MAX_LENGTH_PRODUCTO_ID = 255
MAX_LENGTH_PRODUCTO_DESCRIPCION = 255

MAX_LENGTH_MOVIMIENTO_ID = 255
MAX_LENGTH_MOVIMIENTO_DESCRIPCION_ID = 255
MAX_LENGTH_MOVIMIENTO_DESCRIPCION = 255

MAX_LENGTH_ALMACEN_ID = 255
MAX_LENGTH_ALMACEN_NOMBRE = 255

MAX_LENGTH_GUIA_PROVEEDOR_NRO_SERIE = 255
MAX_LENGTH_GUIA_PROVEEDOR_NRO_CORRELATIVO = 255

MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_ID = 255

MAX_LENGTH_HILADO_ID = 255
MAX_LENGTH_HILADO_TITULO = 255
MAX_LENGTH_HILADO_FIBRA = 255
MAX_LENGTH_HILADO_PROCEDENCIA = 255
MAX_LENGTH_HILADO_ACABADO = 255

MAX_LENGTH_TEJIDO_ID = 255
MAX_LENGTH_TEJIDO_NOMBRE = 255

MAX_LENGTH_CRUDO_ID = 255

MAX_LENGTH_CODIGO_LOTE = 255

MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_ESTADO = 255
MAX_LENGTH_ORDEN_SERVICIO_TEJEDURIA_DETALLE_ESTADO = 255

MAX_LENGTH_COLOR_NOMBRE = 255
MAX_LENGTH_COLOR_DESCRIPCION = 255

MAX_LENGTH_ORDEN_SERVICIO_TINTORERIA_ESTADO = 255
MAX_LENGTH_ORDEN_SERVICIO_TINTORERIA_CODIGO_MECSA = 255

MAX_LENGTH_ADMDTABLA_TABLA = 8
MAX_LENGTH_ADMDTABLA_NOMBRE = 80
MAX_LENGTH_ADMDTABLA_VARCHAR1 = 16
MAX_LENGTH_ADMDTABLA_VARCHAR3 = 16

MAX_LENGTH_MECSA_COLOR_ID = 8
MAX_LENGTH_MECSA_COLOR_NAME = MAX_LENGTH_ADMDTABLA_NOMBRE
MAX_LENGTH_MECSA_COLOR_SKU = MAX_LENGTH_ADMDTABLA_VARCHAR1
MAX_LENGTH_MECSA_COLOR_HEXADECIMAL = 9

COMPANY_CODE_MAX_LENGTH = 6
PURCHASE_ORDER_TYPE_MAX_LENGTH = 2
PURCHASE_ORDER_NUMBER_MAX_LENGTH = 20
SUPPLIER_CODE_MAX_LENGTH = 22
PAYMENT_METHOD_MAX_LENGTH = 120
STATUS_FLAG_MAX_LENGTH = 2

PRODUCT_CODE_MAX_LENGTH = 30
SUPPLIER_CODE_MAX_LENGTH = 30
SUPPLIER_NAME_MAX_LENGTH = 120
SUPPLIER_ADDRESS_MAX_LENGTH = 120
SUPPLIER_RUC_MAX_LENGTH = 22
UNIT_CODE_MAX_LENGTH = 6

MECSA_COLOR_ID_MAX_LENGTH = 8

PRODUCT_ID_MAX_LENGTH = 12

FIBER_ID_MAX_LENGTH = PRODUCT_ID_MAX_LENGTH
FIBER_DENOMINATION_MAX_LENGTH = 100
FIBER_ORIGIN_MAX_LENGTH = 5

STORAGE_CODE_MAX_LENGTH = 6
MOVEMENT_TYPE_MAX_LENGTH = 2
MOVEMENT_CODE_MAX_LENGTH = 4
DOCUMENT_CODE_MAX_LENGTH = 6
DOCUMENT_NUMBER_MAX_LENGTH = 14
DOCUMENT_NOTE_MAX_LENGTH = 187
CLFAUX_MAX_LENGTH = 8
USER_ID_MAX_LENGTH = 24
AUXILIARY_NAME_MAX_LENGTH = 791
AUXILIARY_CODE_MAX_LENGTH = 22
REFERENCE_DOCUMENT_MAX_LENGTH = 6
REFERENCE_NUMBER_MAX_LENGTH = 14
NROGF_MAX_LENGTH = 30
SERGF_MAX_LENGTH = 6
ORIGMOV_MAX_LENGTH = 2
ANNULMENT_USER_ID_MAX_LENGTH = 24
SERIAL_NUMBER_MAX_LENGTH = 6
PRINTED_FLAG_MAX_LENGTH = 2
FLGACT_MAX_LENGTH = 2
FLGRECLAMO_MAX_LENGTH = 2
FLGSIT_MAX_LENGTH = 2
VOUCHER_NUMBER_MAX_LENGTH = 20
SERVADI_MAX_LENGTH = 17
FLGCBD_MAX_LENGTH = 2
ORIGIN_STATION_MAX_LENGTH = 50
UNDPESOBRUTOTOTAL_MAX_LENGTH = 8
TRANSACTION_MODE_MAX_LENGTH = 4
SUPPLIER_BATCH_MAX_LENGTH = 30
MECSA_BATCH_MAX_LENGTH = 30
REFERENCE_CODE_MAX_LENGTH = 6
GROUP_NUMBER_MAX_LENGTH = 12
INGRESS_NUMBER_MAX_LENGTH = 20
EXIT_NUMBER_MAX_LENGTH = 20


BASE_UNIT_CODE_MAX_LENGTH = 6
BASE_UNIT_DESCRIPTION_MAX_LENGTH = 60

DERIVED_UNIT_CODE_MAX_LENGTH = 6
DERIVED_UNIT_DESCRIPTION_MAX_LENGTH = 60
DERIVED_UNIT_SUNAT_CODE_MAX_LENGTH = 6

SUPPLY_FAMILY_ID = "03"
FABRIC_FAMILY_ID = "02"
YARN_SUBFAMILY_ID = "09"

INVENTORY_ITEM_DESCRIPTION_MAX_LENGTH = 120
INVENTORY_ITEM_PURCHASE_DESCRIPTION_MAX_LENGTH = 120
INVENTORY_ITEM_FIELD1_MAX_LENGTH = 16

YARN_ID_MAX_LENGTH = PRODUCT_ID_MAX_LENGTH

YARN_PURCHASE_ENTRY_STORAGE_CODE = "006"
YARN_PURCHASE_ENTRY_MOVEMENT_TYPE = "I"
YARN_PURCHASE_ENTRY_MOVEMENT_CODE = "01"
YARN_PURCHASE_ENTRY_DOCUMENT_CODE = "P/I"

WEAVING_SERVICE_ENTRY_MOVEMENT_CODE = "22"
WEAVING_STORAGE_CODE = "007"

ENTRY_MOVEMENT_TYPE = "I"
ENTRY_DOCUMENT_CODE = "P/I"

DISPATCH_MOVEMENT_TYPE = "S"
DISPATCH_DOCUMENT_CODE = "P/S"
WEAVING_MOVEMENT_CODE = "40"

DYEING_SERVICE_DISPATCH_MOVEMENT_CODE = "42"
DYEING_SERVICE_DISPATCH_DOCUMENT_CODE = "G/R"

SERVICE_CODE_MAX_LENGTH = 6

SERVICE_CODE_YARN_PURCHASE_ENTRY = "HIL"

TRANSPORTER_CODE_MAX_LENGTH = 6
TRANSACTION_MOTIVE_MAX_LENGTH = 6
DRIVER_CODE_MAX_LENGTH = 16
VEHICLE_CODE_MAX_LENGTH = 16
VEHICLE_BRAND_MAX_LENGTH = 30
VEHICLE_PLATE_MAX_LENGTH = 30
DRIVER_LICENSE_MAX_LENGTH = 30
FLGELE_MAX_LENGTH = 2
PREFELE_MAX_LENGTH = 2

HASHCODE_MAX_LENGTH = 512

YARN_WEAVING_DISPATCH_STORAGE_CODE = "006"
YARN_WEAVING_DISPATCH_MOVEMENT_TYPE = "S"
YARN_WEAVING_DISPATCH_MOVEMENT_CODE = "40"
YARN_WEAVING_DISPATCH_DOCUMENT_CODE = "G/R"

SERVICE_CODE_SUPPLIER_WEAVING = "003"
SERVICE_CODE_SUPPLIER_DYEING = "004"

INITIALS_MAX_LENGTH = 6

NROTARJ_MAX_LENGTH = 12
DETDOC_MAX_LENGTH = 100

NRODIR_MAX_LENGTH = 6
NROREQ_MAX_LENGTH = 20

EMAIL_MAX_LENGTH = 80

SERVICE_ORDER_ID_MAX_LENGTH = 20
SERVICE_ORDER_TYPE_MAX_LENGTH = 2

DIRPRO_MAX_LENGTH = 120

FABRIC_ID_MAX_LENGTH = 12
FABRIC_TYPE_MAX_LENGTH = 2

CODCOL_MAX_LENGTH = 8
COLOR_ID_MAX_LENGTH = 8
SUPPLIER_COLOR_ID_MAX_LENGTH = 40

CARD_ID_MAX_LENGTH = 14
CARD_TYPE_MAX_LENGTH = 2
DESTTEJ_MAX_LENGTH = 2


CATEGORY_SERVICE_ORDER_ID = 110

SCHEDULED_SERVICE_ORDER_ID = 1053
ANNULLED_SERVICE_ORDER_ID = 1054
IN_PROCESS_SERVICE_ORDER_ID = 1055
CLOSED_SERVICE_ORDER_ID = 1056
CANCELLED_SERVICE_ORDER_ID = 1057
STOPPED_SERVICE_ORDER_ID = 1058
LIQUIDATED_SERVICE_ORDER_ID = 1059
PENDING_BALANCES_SERVICE_ORDER_ID = 1060


CATEGORY_SERVICE_ORDER_FABRIC_ID = 111

NOT_STARTED_SERVICE_ORDER_FABRIC_ID = 1061
ANNULLED_SERVICE_ORDER_FABRIC_ID = 1062
IN_PROCESS_SERVICE_ORDER_FABRIC_ID = 1063
STOPPED_SERVICE_ORDER_FABRIC_ID = 1064
CANCELLED_SERVICE_ORDER_FABRIC_ID = 1065
COMPLETED_SERVICE_ORDER_FABRIC_ID = 1066
STOCK_TO_BE_PICKED_UP_SERVICE_ORDER_FABRIC_ID = 1067
PICKED_UP_SERVICE_ORDER_FABRIC_ID = 1068


CATEGORY_SERVICE_ORDER_WORKSHOP_ID = 112

NOT_STARTED_SERVICE_ORDER_WORKSHOP_ID = 1069
ANNULLED_SERVICE_ORDER_WORKSHOP_ID = 1070
IN_PROCESS_SERVICE_ORDER_WORKSHOP_ID = 1071
STOPPED_SERVICE_ORDER_WORKSHOP_ID = 1072
CANCELLED_SERVICE_ORDER_WORKSHOP_ID = 1073
COMPLETED_SERVICE_ORDER_WORKSHOP_ID = 1074


CATEGORY_SERVICE_ORDER_YARN_ID = 113

NOT_STARTED_SERVICE_ORDER_YARN_ID = 1075
ANNULLED_SERVICE_ORDER_YARN_ID = 1076
IN_PROCESS_SERVICE_ORDER_YARN_ID = 1077
STOPPED_SERVICE_ORDER_YARN_ID = 1078
CANCELLED_SERVICE_ORDER_YARN_ID = 1079
COMPLETED_SERVICE_ORDER_YARN_ID = 1080
PENDING_BALANCE_TO_BE_ADJUSTED_SERVICE_ORDER_YARN_ID = 1081
PENDING_BALANCE_TO_BE_COLLECTED_SERVICE_ORDER_YARN_ID = 1082


EMPQNRO2_MAX_LENGTH = 30
