MAX_LENGTH_USUARIO_USERNAME = 255
MAX_LENGTH_USUARIO_PASSWORD = 255
MAX_LENGTH_USUARIO_EMAIL = 255
MAX_LENGTH_USUARIO_DISPLAY_NAME = 255

MAX_LENGTH_ROL_NOMBRE = 255

MAX_LENGTH_ACCESO_NOMBRE = 255

MAX_LENGTH_SESION_IP = 255
