MAX_LENGTH_USUARIO_USERNAME = 255
MAX_LENGTH_USUARIO_PASSWORD = 255
MAX_LENGTH_USUARIO_EMAIL = 255
MAX_LENGTH_USUARIO_DISPLAY_NAME = 255

MAX_LENGTH_ROL_NOMBRE = 255

MAX_LENGTH_ACCESO_NOMBRE = 255
MAX_LENGTH_ACCESO_IMAGE_PATH = 255
MAX_LENGTH_ACCESO_VIEW_PATH = 255
MAX_LENGTH_ACCESO_DESCRIPTION = 255
MAX_LENGTH_ACCESO_SCOPE = 255

MAX_LENGTH_SESION_IP = 255

MAX_LENGTH_TOKEN_AUTENTICACION_CODIGO = 255

MAX_LENGTH_MODULO_NOMBRE = 255
MAX_LENGTH_MODULO_IMAGE_PATH = 255

MAX_LENGTH_ROL_COLOR = 255

MIN_PASSWORD_LENGTH = 4
