MAX_LENGTH_USUARIO_USERNAME = 255
MAX_LENGTH_USUARIO_PASSWORD = 255
MAX_LENGTH_USUARIO_EMAIL = 255
MAX_LENGTH_USUARIO_DISPLAY_NAME = 255

MAX_LENGTH_ROL_NOMBRE = 255

MAX_LENGTH_ACCESO_NOMBRE = 255
MAX_LENGTH_ACCESO_IMAGE_PATH = 255
MAX_LENGTH_ACCESO_VIEW_PATH = 255
MAX_LENGTH_ACCESO_DESCRIPTION = 255
MAX_LENGTH_ACCESO_SCOPE = 255

MAX_LENGTH_SESION_IP = 255

MAX_LENGTH_TOKEN_AUTENTICACION_CODIGO = 255

MAX_LENGTH_MODULO_NOMBRE = 255
MAX_LENGTH_MODULO_IMAGE_PATH = 255

MAX_LENGTH_ROL_COLOR = 255

MAX_LENGTH_OPERATION_NAME = 255

PARAMETER_CATEGORY_NAME_MAX_LENGTH = 255

PARAMETER_DESCRIPTION_MAX_LENGTH = 512
PARAMETER_VALUE_MAX_LENGTH = 256
PARAMETER_DATATYPE_MAX_LENGTH = 50

YARNS_ACCESS_ID = 1

VISUALIZE_OPERATION_ID = 101

ENDPOINT_NAME_MAX_LENGTH = 150
ACTION_MAX_LENGTH = 50

ENTITY_TYPE_MAX_LENGTH = 100
